name: projectboard-dev

services:
  ui:
    build:
      context: .
      dockerfile: Dockerfile.ui
    ports:
      - "5173:5173"
    volumes:
      - ./ui/src:/app/src
    depends_on: []

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "3000:3000"
    volumes:
      - ./api/src:/app/src
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/projectboard_core

  mongodb:
    image: mongo:8
    ports:
      - "27017:27017"
